name 'forj-cdk_project'
version '0.1.0'
author '(c) Copyright 2014 Hewlett-Packard Development Company, L.P.'
license 'http://www.apache.org/licenses/LICENSE-2.0'
source 'https://review.forj.io'
project_page 'https://forj.io'
description 'Manage deployment configuration, simillar to openstack_project.  Filtered down version.
'
summary 'Manage deployment configuration, simillar to openstack_project.  Filtered down version.'
