#
# (c) Copyright 2014 Hewlett-Packard Development Company, L.P.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
includes:
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: Build failed.  For information on how to proceed, see https://wiki.openstack.org/wiki/GerritJenkinsGit#Test_Failures
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: patchset-created
        - event: comment-added
          comment_filter: (?i)^\s*recheck(( (?:bug|lp)[\s#:]*(\d+))|( no bug))\s*$
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

  - name: gate
    description: Changes that have been approved by core developers are enqueued in order in this pipeline, and if they pass tests in Jenkins, will be merged.
    failure-message: Build failed.  For information on how to proceed, see https://wiki.openstack.org/wiki/GerritJenkinsGit#Test_Failures
    manager: DependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: comment-added
          approval:
            - approved: 1
        - event: comment-added
          comment_filter: (?i)^\s*reverify(( (?:bug|lp)[\s#:]*(\d+))|( no bug))\s*$
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 2
        submit: true
    failure:
      gerrit:
        verified: -2

  - name: post
    description: This pipeline runs jobs that operate after each change is merged.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^(?!(devnull|refs/.*)).*$

  - name: pre-release
    description: This pipeline runs jobs on projects in response to pre-release tags.
    manager: IndependentPipelineManager
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/([0-9]+\.)+[0-9]*(alpha|beta|candidate|rc|a|b|c|r|g)[0-9]*$

  - name: release
    description: When a commit is tagged as a release, this pipeline runs jobs that publish archives and documentation.
    manager: IndependentPipelineManager
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/([0-9]+\.)+[0-9]+$

  - name: silent
    description: This pipeline is used for silently testing new jobs.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: patchset-created
        - event: comment-added
          comment_filter: (?i)^\s*recheck(( (?:bug|lp)[\s#:]*(\d+))|( no bug))\s*$

  - name: experimental
    description: On-demand pipeline for requesting a run against a set of jobs that are not yet gating. Leave review comment of "check experimental" to run jobs in this pipeline.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: comment-added
          comment_filter: (?i)^\s*check experimental\s*$
    success:
      gerrit:
        force-message: true
    failure:
      gerrit:
        force-message: true

  - name: periodic
    description: Jobs in this queue are triggered on a timer.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      timer:
        - time: '0 6 * * *'


jobs:
  - name: ^.*$
    parameter-function: set_log_url

projects:
  - name: tutorials
    check:
      - tutorials-flake8
    gate:
      - tutorials-flake8
    post:
      - puppet-apply-all-nodes
    release:
      - tutorials-flake8
  - name: forj-config
    check:
      - forj-config-config-layout
      - forj-config-puppet-checks
    gate:
      - forj-config-config-layout
      - forj-config-puppet-checks
    post:
      - puppet-apply-all-nodes
    release:
      - forj-config-puppet-checks
