name 'forj-sysadmin_config'
version '0.1.0'
author '(c) Copyright 2014 Hewlett-Packard Development Company, L.P.'
license 'http://www.apache.org/licenses/LICENSE-2.0'
source 'https://review.forj.io'
project_page 'https://forj.io'
summary 'Manage system configuration, ports / users.  To be refactored for Forj puppet modules orchestration.'
description 'Manage system configuration, ports / users.  To be refactored for Forj puppet modules orchestration.

'
