name    'forj-runtime_project'
version '0.1.0'
source 'https://review.forj.io'
author 'Copyright 2012 Hewlett-Packard Development Company, L.P'
license 'http://www.apache.org/licenses/LICENSE-2.0'
summary 'configuration template module for forj runtime configuration'
description 'We manage our configuration for ci with this module, so it provides an entry point for several ci based configuration that is specific to a running forj instance.

The site.pp and other modules can then rely on this module to be superseeded by the local instance when it\'s populated from source.
Configuration can then later be merged to match up for newer features / options.'
project_page 'https://forj.io'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
