name 'forj-fortify_cli'
version '0.1.0'
author '(c) Copyright 2014 Hewlett-Packard Development Company, L.P.'
license 'http://www.apache.org/licenses/LICENSE-2.0'
source 'https://review.forj.io'
project_page 'https://forj.io'
summary 'Install HP fortify command line scan tools.  Includes check script'
description 'This scan tool will perform a static analysis on a set of source-code input files.
The tool can analyze either a single file, or an entire application consisting of many files.'